name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.8'

    - name: Configure AWS credentials
      run: |
        echo "AWS_ACCESS_KEY_ID=your_access_key_id" >> $GITHUB_ENV
        echo "AWS_SECRET_ACCESS_KEY=your_secret_access_key" >> $GITHUB_ENV

    - name: Sync files to S3 bucket
      run: aws s3 sync . s3://sports-analytic-data-lake --delete
